{
 "title": "Mitsubishi MelCloud",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "room", "label": "Room", "query": { "query": "label_values(room)" } }
  ]
 },
 "panels": [
  {
   "title": "Operation States $room",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "power_state{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", power_state=\"on\", room=~\"$room\"} ",
     "legendFormat": "Power State"
    },
    {
     "expr": "operation_mode{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", operation_mode=\"cool\", room=~\"$room\"} * scalar(power_state{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", power_state=\"on\", room=~\"$room\"} )",
     "legendFormat": "Cooling"
    },
    {
     "expr": "operation_mode{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", operation_mode=\"heat\", room=~\"$room\"} * scalar(power_state{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", power_state=\"on\", room=~\"$room\"} )",
     "legendFormat": "Heating"
    },
    {
     "expr": " operation_mode{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", operation_mode=\"heat_cool\", room=~\"$room\"}  * scalar(power_state{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", power_state=\"on\", room=~\"$room\"} )",
     "legendFormat": "Auto"
    },
    {
     "expr": "operation_mode{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", operation_mode=\"dry\", room=~\"$room\"} * scalar(power_state{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", power_state=\"on\", room=~\"$room\"} )",
     "legendFormat": "Drying"
    },
    {
     "expr": "operation_mode{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", operation_mode=\"fan_only\", room=~\"$room\"} * scalar(power_state{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", power_state=\"on\", room=~\"$room\"} )",
     "legendFormat": "Van Only"
    }
   ]
  },
  {
   "title": "Room Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\nroom_temperature{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", room=\"$room\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperaturs $room",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "room_temperature{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", room=~\"$room\"}",
     "legendFormat": "Room Temp {{label_name}}"
    },
    {
     "expr": "target_temperature{instance=\"192.168.1.12:9004\", job=\"mel-cloud-exporter\", room=~\"$room\"}",
     "legendFormat": "Room Temp  Target {{label_name}}"
    }
   ]
  }
 ]
}